# Generated by Django 4.2.5 on 2023-10-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubgstats', '0003_board_created_at_board_updated_at_alter_board_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='last_link',
            field=models.CharField(default='No link yet', max_length=400),
            preserve_default=False,
        ),
    ]
